name: Terraform
description: Runs Terraform in your pipeline.
author: https://github.com/echoboomer
requirements:
  - docker
configuration:
  properties:
    apply:
      type: boolean
    apply_only:
      type: boolean
    apply_master:
      type: boolean
    debug:
      type: boolean
    disable_ssh_keyscan:
      type: boolean
    env:
      type: [string, array]
    image:
      type: string
    init_args:
      type: [string, array]
    known_hosts_location:
      type: string
    no_validate:
      type: boolean
    precommand:
      type: string
    skip_apply_no_diff:
      type: boolean
    use_workspaces:
      type: boolean
    auto_create_workspace:
      type: boolean
    version:
      type: string
    volumes:
      type: [string, array]
    working_directory:
      type: string
    workspace:
      type: string
    workspace_metadata_key:
      type: string
